/*
 * GE_Defines.h
 *
 *  Created on: Apr 26, 2010
 *      Author: Nils Inge Bjelland

 *  Modified on: Dec 5, 2017
 *  	Version info (GE_COMMON_VERSION) moved into GE_CommonVersion.h which is autogenerated by make 
 *      using information from the versioncontrol system (at the monent git)
 * 	Author: Kjell Eirik Solvang
 */

#ifndef GE_DEFINES_H_
#define GE_DEFINES_H_
#include "GE_CommonVersion.h"


#define GE_OK 0
#define GE_ERROR 1
#define GE_OVERFLOW 2
#define GE_INVALID_PARAMETER 3
#define GE_RESOURCE_UNAVAILABLE 4
#define GE_FILE_IN_USE 5
#define GE_ADDRESS_EXISTS 6
#define GE_INVALID_ADDRESS 7
#define GE_NOT_EXISTING 8
#define GE_UNDERRUN 9
#define GE_ABORT 10
#define GE_COMMFAIL 11
#define GE_BUSY 12
#define GE_NO_ACCESS 13
#define GE_NOT_PERMITTED 14

#endif /* GE_DEFINES_H_ */
